fix: non deterministic cost
dashpay/grovedb pull request #256
Opened 2023-06-01 12:48 UTC by iammadab

## Issue being fixed or feature implemented

Cost values depended on the ordering of key values in the rocksdb storage layer, leading to different state roots when prefix computation changes. 

## What was done?

Unified the costs, regardless of the ordering in the underlying storage layer. 
- if the next key is from another merk, rather than add the cost of the key we add the max key length
- if the next key is none, add the max key length rather than nothing. 

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated relevant unit/integration/functional/e2e tests
- [X] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-06-01 16:09 UTC, fominok approved these changes
gentlemen, we did it

2023-06-02 07:38 UTC, QuantumExplorer requested changes
We need more comments.

2023-06-02 07:38 UTC, QuantumExplorer commented on storage/src/rocksdb_storage/storage_context/raw_iterator.rs
> +                    cost.storage_loaded_bytes += MAX_PREFIXED_KEY_LENGTH;
Add a comment explaining this situation.

2023-06-02 07:38 UTC, QuantumExplorer commented on storage/src/rocksdb_storage/storage_context/raw_iterator.rs
> +                cost.storage_loaded_bytes += MAX_PREFIXED_KEY_LENGTH;
Add a comment explaining this situation.

2023-06-02 07:38 UTC, QuantumExplorer commented on storage/src/rocksdb_storage/storage_context/raw_iterator.rs
> +                    cost.storage_loaded_bytes += MAX_PREFIXED_KEY_LENGTH;
Add a comment explaining this situation.

2023-06-02 07:38 UTC, QuantumExplorer commented on storage/src/rocksdb_storage/storage_context/raw_iterator.rs
> +                cost.storage_loaded_bytes += MAX_PREFIXED_KEY_LENGTH;
Add a comment explaining this situation.

2023-06-02 09:05 UTC, QuantumExplorer approved these changes

2023-06-02 09:16 UTC, merged